import { Injectable } from '@angular/core';
import { Observable, BehaviorSubject, from, of, throwError } from 'rxjs';
import { AngularFirestore } from '@angular/fire/compat/firestore';

import { BookModel } from '../../models/book.model';

import { UtilService } from '../utilservice/util.service';


@Injectable({
  providedIn: 'root'
})
export class BookService {
  constructor(private UtilService: UtilService, private firestore: AngularFirestore) {}
  private _BOOKdb: Array<BookModel> = []
  private KEY: string = 'books'
  private mockDB(): void {
    this._BOOKdb = this.UtilService.load(this.KEY) || this.UtilService.store(this.KEY, [new BookModel('5a56640269f443a5d64b32ca', 'The Lightning Thief', "Percy Jackson is a good kid, but he can't seem to focus on his schoolwork or control his temper. And lately, being away at boarding school is only getting worse - Percy could have sworn his pre-algebra teacher turned into a monster and tried to kill him. When Percy's mom finds out, she knows it's time that he knew the truth about where he came from, and that he go to the one place he'll be safe. She sends Percy to Camp Half Blood, a summer camp for demigods (on Long Island), where he learns that the father he never knew is Poseidon, God of the Sea. Soon a mystery unfolds and together with his friends—one a satyr and the other the demigod daughter of Athena - Percy sets out on a quest across the United States to reach the gates of the Underworld (located in a recording studio in Hollywood) and prevent a catastrophic war between the gods.", 'Rick Riordan', '1.png'),
    new BookModel('5a5664025f6ae9aa24a99fde', 'The Bad Beginning', "Dear Reader, I'm sorry to say that the book you are holding in your hands is extremely unpleasant. It tells an unhappy tale about three very unlucky children. Even though they are charming and clever, the Baudelaire siblings lead lives filled with misery and woe. From the very first page of this book when the children are at the beach and receive terrible news, continuing on through the entire story, disaster lurks at their heels. One might say they are magnets for misfortune.In this short book alone, the three youngsters encounter a greedy and repulsive villain, itchy clothing, a disastrous fire, a plot to steal their fortune, and cold porridge for breakfast. It is my sad duty to write down these unpleasant tales, but there is nothing stopping you from putting this book down at once and reading something happy, if you prefer that sort of thing. With all due respect Lemony Snicket", ' ', '2.png'),
    new BookModel('5a56640252d6acddd183d319', 'Minno', "It isn't easy being thirteen ... and being raised by your grandfather ... and having a name like Minno ... and then having to journey through a strange land. But Minno is doing the best she can. For all her young life Minno believed her parents were dead. Then she learns they're alive, but they're in grave danger. Her friend Hailey thought she was having a sleepover at her friend's house. Now she's Minno's ally and partner on an incredible quest. Together the girls embark on the adventure of a lifetime, where they face a veritable menagerie of strange creatures, both friendly and unfriendly to their cause. Oh, yea, then there's one evil high minister Craveaux, who must stop Minno while he steals all the magic in the kingdom for his own sinister purposes. Minno has to save her parents, and along the way discover who she really is.", 'James Barlog', '3.png'),
    new BookModel('5a566402ed1cf349f0b47b4d', 'Amanda Lester and the Pink Sugar Conspiracy', "Twelve-year-old Amanda Lester wouldn't be caught dead going into the family business. Just because she's related to Inspector G. Lestrade, that bumbler who sometimes worked with master sleuth Sherlock Holmes, doesn't mean she should become a detective and give up her dream of becoming a filmmaker. Unfortunately, her plans are in jeopardy. Her latest project with the Stick Dog Filmmakers Club and Production Company isn't coming together, and her control freak tendencies have driven away all her actors. If she doesn't make a winning film soon, her parents will insist that she go into the L.A.P.D. young cadets training program, and her budding career will be over. So when Herb and Lila Lester suddenly send her to a secret English school for the descendants of famous detectives, Amanda resists-until she and her new friends notice drops of blood and weird pink substances in odd places. Are these strange happenings clues to a real mystery or simply part of the elaborate class project the teachers assign every year? The answer comes all too soon. When Amanda's father disappears and the school's cook is found dead with her head in a bag of sugar, the kids are certain that crimes are taking place. Now Amanda must embrace her destiny and uncover the truth. The only snag is that arch-villain Blixus Moriarty, a descendant of Holmes's nemesis Professor James Moriarty, might be involved, and he doesn't like nosy little girls interfering in his business.", 'Paula Berinstein', '4.png'),
    new BookModel('5a566402abce24c6bfe4699d', 'The Maze of Bones', "When their beloved aunt--matriarch of the world's most powerful family--dies, orphaned siblings Amy and Dan Cahill compete with less honorable Cahill descendants in a race around the world to find cryptic clues to a mysterious fortune. Book includes game cards which the reader may use to play an online version of the treasure hunt.", 'Rick Riordan', '5.png'),
    new BookModel('5a566402a6499c1d4da9220a', 'School of Fear', 'With very few options left, the parents of these four twelve year-olds send them to the highly elusive and exclusive School of Fear to help them overcome their phobias. But when their peculiar teacher, Mrs. Wellington, and her unconventional teaching methods turn out to be more frightening than even their fears, the foursome realize that this just may be the scariest summer of their lives.', 'Gitty Daneshvari, Emma Walton Hamilton', '6.png'),
    new BookModel('5a566402f90ae30e97f990db', 'Artemis Fowl', "Twelve-year-old Artemis Fowl is a millionaire, a genius, and above all, a criminal mastermind. But even Artemis doesn't know what he's taken on when he kidnaps a fairy, Captain Holly Short of the LEPrecon Unit. These aren't the fairies of bedtime stories—they're dangerous! Full of unexpected twists and turns, Artemis Fowl is a riveting, magical adventure.", 'Eoin Colfer', '7.png'),
    new BookModel(this.UtilService.setId(), 'A Suitable Boy', "Vikram Seth's novel is, at its core, a love story: Lata and her mother, Mrs. Rupa Mehra, are both trying to find—through love or through exacting maternal appraisal—a suitable boy for Lata to marry. Set in the early 1950s, in an India newly independent and struggling through a time of crisis, A Suitable Boy takes us into the richly imagined world of four large extended families and spins a compulsively readable tale of their lives and loves. A sweeping panoramic portrait of a complex, multiethnic society in flux, A Suitable Boy remains the story of ordinary people caught up in a web of love and ambition, humor and sadness, prejudice and reconciliation, the most delicate social etiquette and the most appalling violence.", 'Vikram Seth', '8.png'),
    new BookModel(this.UtilService.setId(), 'Infernal Devices', "HE INHERITED A WATCHMAKER'S STORE - AND A WHOLE HEAP OF TROUBLE. But idle sometime-musician George has little talent for clockwork. And when a shadowy figure tries to steal an old device from the premises, George finds himself embroiled in a mystery of time travel, music and sexual intrigue. A genuine lost classic, a steampunk original whose time has come.", 'K.W. Jeter', '9.png'),
    new BookModel(this.UtilService.setId(), 'The Reapers are the Angels', "Zombies have infested a fallen America. A young girl named Temple is on the run. Haunted by her past and pursued by a killer, Temple is surrounded by death and danger, hoping to be set free. For twenty-five years, civilization has survived in meager enclaves, guarded against a plague of the dead. Temple wanders this blighted landscape, keeping to herself - and keeping her demons inside. She can't remember a time before the zombies, but she does remember an old man who took her in and the younger brother she cared for until the tragedy that set her on a personal journey toward redemption. Moving back and forth between the insulated remnants of society and the brutal frontier beyond, Temple must decide where ultimately to make a home and find the salvation she seeks.", 'Alden Bell', '10.png'),
    new BookModel(this.UtilService.setId(), 'How to Fall Out of Love Madly', "Joy and Annie are friends and roommates whose thirtysomething existences aren't exactly what they'd imagined for themselves. Struggling to make ends meet, they decide to rent their extra bedroom to Theo, who charms Joy with his salt-and-pepper hair and adoration of their one-eyed cat. When Annie goes to live with her boyfriend, Theo and Joy settle into a comfortable domesticity. Then Theo brings home Celine, the girlfriend he's never mentioned and who is possibly the most stunning woman Joy has ever seen. Joy resolves to do whatever it takes to nurture the bond she and Theo have forged. Anything Celine might deny him, Joy will grant. Distracted by her need to please Theo, Joy fails to see that Celine's beauty doesn't protect her from her own insecurities. Celine is so haunted by an event in her past that she can't access the confidence she yearns to exude.", 'Jana Casale', '11.png'),
    new BookModel(this.UtilService.setId(), 'Sacrificio', "Set in Cuba in 1998, Sacrificio is a triumphant and mesmeric work of violence, loss, and identity, following a group of young HIV-positive counterrevolutionaries who seek to overthrow the Castro government. Rafa, an Afro-Cuban orphan, moves to Havana with nothing to his name and falls into a job at a café. He is soon drawn into a web of bizarre, ever-shifting entanglements with his boss’s son, the charismatic Renato, leader of the counterrevolutionary group “Los Injected Ones,” which is planning a violent overthrow of the Castro government during Pope John Paul II's upcoming visit.", 'Ernesto Mestre-Reed', '12.png'),
    ])
  }
  books: BookModel[] = []
  _books$ = new BehaviorSubject<Array<BookModel>>([])
  books$ = this._books$.asObservable()

  public loadBooks(): void {
    this.mockDB()
    this.books = this._BOOKdb
    let books = this.books
    this._books$.next(books)
  }

  public getById(bookId: string): Observable<BookModel | void> {
    const book = this.books.find(book => book._id === bookId)
    if (book) return of({ ...book })
    return of()
}
}
